- name: Deploy Mule application to CloudHub 2.0 -DskipExchangePreDeploy=true \
  run: |
    mvn clean deploy -Pcloudhub-2.0 \
      -Danypoint.client_id=e85c250d7185443eaf380821bdd543c9 \
      -Danypoint.client_secret=Ec0b12d15A31457bB80B502CeD1b9835 \
      -Danypoint.env=Sandbox \
      -Danypoint.org="c39dc6dd-e124-4390-867b-7b58e9d44727"
